stages:
  - test

test:
  stage: test
  script:
#    - activate xw27
    - python -c "import sys; print(sys.version)"
    - cd xlwings
    - nosetests
#    - msbuild src/xlwings.sln /p:Configuration=Release